### PR TITLE
Github action to build and inject the sideload tweak

### PR DESCRIPTION
**Pull request by mustafacakirogludev**
As you know the ipa files are removed due to a DMCA and we won't be providing them from now on. I created a github action to build and inject the YTMU tweak into a decrypted IPA provided by the user. This way we won't be sharing IPA files but the users will be able to fork this repo and build their own tweaked IPAs. Since this github action creates the ipa in a draft release in the user's forked repository, users won't get DMCAs.

### CODE REVIEW

**Comment by Saud-97** [comment]
Thank you sooo much for what you are doing.

**Comment by ttyman0109a** [comment]
how about prompting the user for the link for the IPA file and invoking azule to patch the file in the github action and then returns the patched file to the users repository

**Comment by ginsudev** [comment]
Hi @mustafacakirogludev , are you able to attach a screenshot of the action's output so we can be sure it works as expected? Thanks

**Comment by mustafacakirogludev** [comment]
@ginsudev is this enough? Alternatively you can quickly fork my fork and run it yourself to make sure it works. Let me know if you need further screenshots.
image

**Comment by ginsudev** [comment]
@mustafacakirogludev all good

**Pull request merged**
